### ISSUE TITLE
When sound is sent, it crashes and stops receiving messages

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/recordium#18]
Maybe, check!

**Comment by lorenariveira** [comment]
Hi! 
I've just installed it and although I received 1 text message, I stopped getting any notifications after I tried the audio messages.
I tried quitting and restarting recordium but I failed to receive texts and audios. Each time I restart I get this:
```Saving logs to '/home/maggie/.cache/recordium/recordium.log'
Running Python sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0) on 'linux'
Recordium: v. 1
2017-04-05 22:46:15,031  recordium               ERROR    Unhandled exception!
Traceback (most recent call last):
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 479, in _inline_callbacks
    result = gen.send(result)
  File "/home/maggie/recordium/recordium/network.py", line 69, in from_update
    text=text, sent_at=sent_at, message_id=update_id, extfile_path=extfile_path))
UnboundLocalError: local variable 'text' referenced before assignment

2017-04-05 22:46:15,032  recordium               ERROR    Unhandled exception!
Traceback (most recent call last):
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
  File "/home/maggie/recordium/recordium/network.py", line 187, in _process
    ni = yield NotificationItem.from_update(item)
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 479, in _inline_callbacks
    result = gen.send(result)
  File "/home/maggie/recordium/recordium/network.py", line 69, in from_update
    text=text, sent_at=sent_at, message_id=update_id, extfile_path=extfile_path))
UnboundLocalError: local variable 'text' referenced before assignment

2017-04-05 22:46:15,034  recordium               ERROR    Unhandled exception!
Traceback (most recent call last):
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 390, in _next
    self.result = callback(self.result, *args, **kwargs)
  File "/home/maggie/recordium/recordium/network.py", line 210, in _re_get
    error.raise_exception()
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 125, in raise_exception
    raise self.type(self.value).with_traceback(self.traceback)
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
  File "/home/maggie/recordium/recordium/network.py", line 187, in _process
    ni = yield NotificationItem.from_update(item)
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 479, in _inline_callbacks
    result = gen.send(result)
  File "/home/maggie/recordium/recordium/network.py", line 69, in from_update
    text=text, sent_at=sent_at, message_id=update_id, extfile_path=extfile_path))
UnboundLocalError: local variable 'text' referenced before assignment

2017-04-05 22:46:15,035  recordium               ERROR    Unhandled exception!
Traceback (most recent call last):
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 390, in _next
    self.result = callback(self.result, *args, **kwargs)
  File "/home/maggie/recordium/recordium/network.py", line 210, in _re_get
    error.raise_exception()
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 125, in raise_exception
    raise self.type(self.value).with_traceback(self.traceback)
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 477, in _inline_callbacks
    result = gen.throw(result.type(result.value).with_traceback(result.traceback))
  File "/home/maggie/recordium/recordium/network.py", line 187, in _process
    ni = yield NotificationItem.from_update(item)
  File "/home/maggie/.local/share/fades/f4d08a07-ba47-42a0-8e87-36696d8b5448/lib/python3.6/site-packages/defer/__init__.py", line 479, in _inline_callbacks
    result = gen.send(result)
  File "/home/maggie/recordium/recordium/network.py", line 69, in from_update
    text=text, sent_at=sent_at, message_id=update_id, extfile_path=extfile_path))
UnboundLocalError: local variable 'text' referenced before assignment```

**Comment by gilgamezh** [comment]
If I print `msg` the type is `voice` is it implemented?

```json
{
    "message_id": 3,
    "from": {
        "id": 12345,
        "first_name": "XXX",
        "username": "XXXX"
    },
    "chat": {
        "id": 1234567,
        "first_name": "XXXXXX",
        "username": "XXXXX",
        "type": "private"
    },
    "date": 1491442201,
    "voice": {
        "duration": 3,
        "mime_type": "audio/ogg",
        "file_id": "XXXXXXXXXXXXXXXXX",
        "file_size": 24638
    }
}
```

**Comment by facundobatista** [comment]
No, it's not (see #2 ) but it shouldn't crash anyway (and it should keep receive messages)
